prd:
  STAGE: "prd"
  JWT_SECRET: "Tel@-Vermelh@-pet"
pet:
  STAGE: "pet"
  JWT_SECRET: "Tel@-Vermelh@-pet"

REGION: "us-east-1"
ACCOUNT_ID: "769533000303"

REDIS_HOST: "redis.dev.coedigital.clarobrasil.mobi"
REDIS_PORT: "6379"
EXPIRATION_TIME: 12086400
