prd:
  STAGE: "prd"
  JWT_SECRET: "C0deHer0es-prd"
  DATABASE_URL: "postgresql://neondb_owner:p7RQFbLUg9kM@ep-tight-dew-a50ipcsw.us-east-2.aws.neon.tech/neondb?sslmode=require"
pet:
  STAGE: "pet"
  JWT_SECRET: "C0deHer0es-pet"
  DATABASE_URL: "postgresql://neondb_owner:p7RQFbLUg9kM@ep-tight-dew-a50ipcsw.us-east-2.aws.neon.tech/neondb?sslmode=require"

REGION: "us-east-1"
ACCOUNT_ID: "125993934816"
