prd:
  STAGE: "prd"
  REGION: "us-east-1"
  ACCOUNT_ID: "769533000303"
  JWT_SECRET: "Tel@-Vermelh@-pet"
pet:
  STAGE: "pet"
  REGION: "us-east-1"
  ACCOUNT_ID: "769533000303"
  JWT_SECRET: "Tel@-Vermelh@-pet"
