service: poc-appsync

build:
  esbuild:
    bundle: true
    minify: false
    external:
      - "@aws-sdk/client-s3" # Módulos que você realmente quer excluir do bundle
    exclude:
      - "@aws-sdk/*" # Não exclua módulos que você precisa no bundle
    sourcemap:
      type: linked
      setNodeOptions: true

plugins:
   - serverless-appsync-plugin

package:
  exclude:
    - "**" # Exclui tudo por padrão
  include:
    - dist/**
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'pet'}
  region: us-east-1
  tracing:
    lambda: true
  iam:
    role:
      ${file(./ymls/roles.yml)}

  stackTags:
      projectName: ${self:service}-${self:provider.stage}
      project: ${self:service}-${self:provider.stage}
      stage: ${sls:stage}
      env: ${opt:stage, 'pet'}
      version: ${file(./package.json):version}

  environment:
    STAGE: ${file(./ymls/environment.yml):${opt:stage}.STAGE}
    REGION: ${file(./ymls/environment.yml):REGION}
    ACCOUNT_ID: ${file(./ymls/environment.yml):ACCOUNT_ID}

custom:
  stage: ${self:provider.stage}
  appSync:
    ${file(ymls/appsync.yml)}

functions: ${file(ymls/functions.yml)}

# resources: ${file(ymls/resources.yml)}
